/**
 * Type definitions for Monoton API
 */

// Invoice types
export interface CreateInvoiceRequest {
  buyer: string;            // Buyer's Canton party ID
  amount: number;            // Invoice amount
  currency?: string;         // Currency code (ISO 4217 or "CC")
  description: string;       // Invoice description
  dueDate?: string;          // ISO 8601 date string
  metadata?: Record<string, string>;  // Optional metadata
}

export interface InvoiceResponse {
  invoiceId: string;
  seller: string;
  buyer: string;
  amount: number;
  currency: string;
  description: string;
  status: InvoiceStatus;
  dueDate?: string;
  createdAt?: string;
}

export type InvoiceStatus = 
  | 'Created' 
  | 'Approved' 
  | 'AwaitingSettlement' 
  | 'Settled' 
  | 'Rejected';

export interface ApproveInvoiceRequest {
  // No body required - authorization determines buyer
}

export interface SettleInvoiceRequest {
  autoMerge?: boolean;        // Auto-merge small holdings before transfer
}

// Wallet types
export interface BalanceResponse {
  party: string;
  balances: Balance[];
  totalInstruments: number;
}

export interface Balance {
  amount: number;
  currency: string;
}

export interface Holding {
  contractId: string;
  amount: number;
  currency: string;
  instrumentAdmin: string;
}

// Error types
export interface ApiError {
  error: string;
  message?: string;
  details?: unknown;
}

// Ledger types (will be generated by codegen)
export interface Invoice {
  seller: string;
  buyer: string;
  operator: string;
  invoiceId: string;
  amount: number;
  currency: string;
  description: string;
  status: InvoiceStatus;
  dueDate?: string;
  createdAt?: string;
  instrumentAdmin: string;
  transferInstructionCid?: string;
}

export interface BusinessRegistration {
  business: string;
  operator: string;
  businessName: string;
  taxId: string;
  status: 'Active' | 'Suspended' | 'Revoked';
  registeredAt: string;
}

export interface SettlementDelegation {
  seller: string;
  operator: string;
  scope: string;
  validFrom: string;
  validUntil: string;
  active: boolean;
}
